try {
    nonExistentFunction();
}
catch (errorVariable){
    console.log(errorVariable);
}